# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otusPam => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      config.vm.synced_folder "./", "/vagrant"
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "512"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            # 1part
            yum install epel-release -y
            yum install pam_script -y
            echo "auth  required  pam_script.so" >> /etc/pam.d/sshd
            chmod +x /vagrant/pam_script
            cp /vagrant/pam_script /etc/
            groupadd admin
            useradd -G admin bun
            useradd cookie
            echo "bun:Otus2019" | chpasswd
            echo "cookie:Otus2019" | chpasswd
            bash -c "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
            systemctl restart sshd
            # 2part
            useradd dockerUser
            echo "dockerUser:Otus2019" | chpasswd
            yum check-update
            curl -fsSL https://get.docker.com/ | sh
            systemctl start docker
            usermod -aG docker dockerUser
            echo %dockerUser ALL=NOPASSWD: /bin/systemctl restart docker.service>>/etc/sudoers
            chmod 0440 /etc/sudoers.d/vagrant
            systemctl restart docker
          SHELL
      end
  end
end	
